apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: dtorders
  name: dtorders
  namespace: monolith
spec:
  containers:
  - image: domuharahap/dtdemos-monolith
    name: dtorders
    ports:
    - containerPort: 8080
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
